//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoardSquare
    {
        public int SquareId { get; set; }
        public int Row { get; set; }
        public int Column { get; set; }
        public bool Mine { get; set; }
        public bool Discovered { get; set; }
        public bool Marked { get; set; }
        public int NumberOfNeighbors { get; set; }
        public Nullable<int> GameBoard_ID { get; set; }
    
        public virtual GameBoard GameBoard { get; set; }
    }
}
