//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int GameID { get; set; }
        public System.DateTime Date { get; set; }
        public string Winner { get; set; }
        public Nullable<int> Board_ID { get; set; }
        public string Player_UserName { get; set; }
        public string Player1_UserName { get; set; }
        public string Player2_UserName { get; set; }
    
        public virtual GameBoard GameBoard { get; set; }
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
        public virtual Player Player2 { get; set; }
    }
}
